### ISSUE TITLE
assert old_decoder.bias is None

### ISSUE THREAD

**Issue by YsylviaUC** [mnhng/HeadFilt#1]
hi, when I run  csc_base.py, an error is reported: **assert old_decoder.bias is None.**  This problem appeared in util. resize_bert(), So I changed the _vocab = tfm.BertTokenizer.from_pretrained('bert-base-chinese-ext')_ to _vocab = tfm.BertTokenizer.from_pretrained('bert-base-chinese')_ to make the vocab is not changed, and then delete this line  _util.resize_bert(model, len(vocab))_. I am wondering the correct way to solve this problem.

**Comment by mnhng** [comment]
What pretrained model did you use? Was it "bert-base-chinese" or something else? Did you use the same version of **transformers** library specified in **env.yml**? The code should run without triggering the assert if the **transformers** version and the pretrained model are unchanged.

You can try commenting out the assert if you are using a newer version of **transformers** but there is no guarantee that it would run correctly.

If the tokenizer is **bert-base-chinese** instead of **bert-base-chinese-ext**, the code should still run. However, the performance may be a bit less accurate because some of the rare Chinese characters will be tokenized into [UNK].

**Comment by YsylviaUC** [comment]
Thank you for your quick reply. Yes, I used bert-base-chinese, which is downloaded from：https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-chinese.tar.gz.
And the version of transformers is 4.1.1.
Finally I got the result（csc_base.py):
FA DA DP DR DF1 CA CP CR CF1
NaN 0.6618 1.0 0.6618 0.7965 0.5218 1.0 0.5218 0.6858
The experimental results are quite different from the results you released in your paper.



At 2021-09-30 00:04:29, "mnhng" ***@***.***> wrote:

What pretrained model did you use? Was it "bert-base-chinese" or something else? Did you use the same version of transformers library specified in env.yml? The code should run without triggering the assert if the transformers version and the pretrained model are unchanged.

You can try commenting out the assert if you are using a newer version of transformers but there is no guarantee that it would run correctly.

If the tokenizer is bert-base-chinese instead of bert-base-chinese-ext, the code should still run. However, the performance may be a bit less accurate because some of the rare Chinese characters will be tokenized into [UNK].

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mnhng** [comment]
@YuxiBupt 
There were some errors in the configuration files (see ff844faa4624bda83dc7c577cd2ec2fa528a95fd) . You can just update the code and try again.
